Repository zhengyangWang1/NNDL_Project, pull requests merged in 2023-12, with the labels that each got.

#24 refactor: 重构data_loader
  utils/data_loader.py
Labels: enhancement

#25 feat:实现positional embedding并添加到模型中
  model/decoder/transformer_decoder.py
  model/encoder/transformer_encoder.py
  model/loss_function.py
  utils/data_loader.py
Labels: need to be done

#27 feat: 完善CNNTransformer训练循环，完善训练函数
  config.json
  data/README.md
  main.py
  model/encoder/resnet.py
  model/encoder/transformer_encoder.py
  model/loss_function.py
  utils/config.py
  utils/data_loader.py
  utils/trainer.py
Labels: need to be done

#28 fix: 解决爆显存的问题：使用1*1卷积降低了resnet输出的通道数
  config.json
  model/__init__.py
  model/decoder/transformer_decoder.py
  model/encoder/transformer_encoder.py
  model/model.py
  utils/config.py
  utils/gpu_mem_track.py
  utils/modelsize_estimate.py
  utils/trainer.py
Labels: bug

#29 Wzy
  main.py
  model/__init__.py
  model/decoder/gru.py
  model/decoder/transformer_decoder.py
  model/encoder/transformer_encoder.py
  utils/data_loader.py
  utils/trainer.py
Labels: enhancement

#32 fix: conflict
  config.json
  main.py
  utils/config.py
  utils/trainer.py
Labels: bug

#34 refactor: config重构
  config.json
  utils/config.py
  utils/trainer.py
Labels: enhancement

#36 feat: 添加了进度条
  utils/data_loader.py
  utils/trainer.py
Labels: enhancement

#37 feat: 添加了evaluate函数评估模型性能
  config.json
  main.py
  utils/trainer.py
Labels: enhancement, need to be done

#40 feat: 添加了mask模块 fix: 修正了Transformer预测的错误
  config.json
  main.py
  model/decoder/transformer_decoder.py
  model/encoder/transformer_encoder.py
  model/loss_function.py
  model/model.py
  utils/config.py
  utils/data_loader.py
  utils/metrics.py
  utils/trainer.py
Labels: bug, need to be done

#42 feat: metrics bleu初步实现
  config.json
  main.py
  model/model.py
  utils/config.py
  utils/data_loader.py
  utils/metrics.py
  utils/trainer.py
Labels: enhancement, need to be done
